"""papers

Revision ID: 0f03e405973f
Revises: f948dc71518f
Create Date: 2026-06-21 21:01:04.584545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f03e405973f'
down_revision: Union[str, Sequence[str], None] = 'f948dc71518f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('bibliography_verified', sa.Boolean(), nullable=False),
    sa.Column('bibliography_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers')),
    sa.UniqueConstraint('doi', name=op.f('uq_papers_doi')),
    sa.UniqueConstraint('source_key', name=op.f('uq_papers_source_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('papers')
    # ### end Alembic commands ###
