"""add work_key and is_preferred_edition to books

Revision ID: 17f7ef2469f8
Revises: 8ca2606771f4
Create Date: 2026-06-18 15:55:14.489105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f7ef2469f8'
down_revision: Union[str, Sequence[str], None] = '8ca2606771f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_preferred_edition', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('is_preferred_edition', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('is_preferred_edition')
        batch_op.drop_column('work_key')

    # ### end Alembic commands ###
