"""add bibliography_source and lookup_confidence to books

Revision ID: 4627f58c2d3e
Revises: 584e752a85ac
Create Date: 2026-06-20 07:00:21.118141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4627f58c2d3e'
down_revision: Union[str, Sequence[str], None] = '584e752a85ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bibliography_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lookup_confidence', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('lookup_confidence')
        batch_op.drop_column('bibliography_source')

    # ### end Alembic commands ###
