"""updates

Revision ID: 74ff1ab2a952
Revises: b98416e49ed0
Create Date: 2026-06-26 12:00:37.643924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ff1ab2a952'
down_revision: Union[str, Sequence[str], None] = 'b98416e49ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_context', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_documents', schema=None) as batch_op:
        batch_op.drop_column('document_context')

    # ### end Alembic commands ###
