"""corpus intergrate

Revision ID: 8401efabb5d1
Revises: 618596fef8f0
Create Date: 2026-06-27 12:02:36.552753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8401efabb5d1'
down_revision: Union[str, Sequence[str], None] = '618596fef8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_context_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('context_known', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('marked_for_delete', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_corpus_context_checks_book_id_books'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_corpus_context_checks_paper_id_papers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpus_context_checks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corpus_context_checks')
    # ### end Alembic commands ###
