"""add is_editor flag to books

Revision ID: 8ca2606771f4
Revises: 3b0a19cd07b9
Create Date: 2026-06-18 14:24:40.896956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca2606771f4'
down_revision: Union[str, Sequence[str], None] = '3b0a19cd07b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_editor', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('is_editor', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('is_editor')

    # ### end Alembic commands ###
