"""add paper_id to citations

Revision ID: af9a5a3c31ce
Revises: 0f03e405973f
Create Date: 2026-06-22 20:32:25.213032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9a5a3c31ce'
down_revision: Union[str, Sequence[str], None] = '0f03e405973f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_citations_paper_id_papers'), 'papers', ['paper_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_citations_paper_id_papers'), type_='foreignkey')
        batch_op.drop_column('paper_id')

    # ### end Alembic commands ###
