"""Chats Model Update

Revision ID: b69909aba0a4
Revises: af9a5a3c31ce
Create Date: 2026-06-23 19:14:13.667522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69909aba0a4'
down_revision: Union[str, Sequence[str], None] = 'af9a5a3c31ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chats_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chats_user_id_users'), 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_citations_paper_id_papers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_citations_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_citations_paper_id_papers'), 'papers', ['paper_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_citations_book_id_books'), 'books', ['book_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_citations_book_id_books'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_citations_paper_id_papers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_citations_book_id_books'), 'books', ['book_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_citations_paper_id_papers'), 'papers', ['paper_id'], ['id'])

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chats_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chats_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
