"""update tables

Revision ID: b98416e49ed0
Revises: eb6623f4fa80
Create Date: 2026-06-25 20:37:34.831172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98416e49ed0'
down_revision: Union[str, Sequence[str], None] = 'eb6623f4fa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_cross_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('agrees', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('is_checkable_claim', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['claim_verifications.id'], name=op.f('fk_claim_cross_checks_verification_id_claim_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_cross_checks')),
    sa.UniqueConstraint('verification_id', name=op.f('uq_claim_cross_checks_verification_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_cross_checks')
    # ### end Alembic commands ###
