"""verifications

Revision ID: eb6623f4fa80
Revises: b69909aba0a4
Create Date: 2026-06-23 21:01:36.050181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6623f4fa80'
down_revision: Union[str, Sequence[str], None] = 'b69909aba0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_documents_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_documents'))
    )
    op.create_table('extracted_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['verification_documents.id'], name=op.f('fk_extracted_claims_document_id_verification_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_claims'))
    )
    op.create_table('claim_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['extracted_claims.id'], name=op.f('fk_claim_verifications_claim_id_extracted_claims')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_verifications')),
    sa.UniqueConstraint('claim_id', name=op.f('uq_claim_verifications_claim_id'))
    )
    op.create_table('claim_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('web_url', sa.String(), nullable=True),
    sa.Column('web_title', sa.String(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('locator', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_claim_evidence_book_id_books'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_claim_evidence_paper_id_papers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verification_id'], ['claim_verifications.id'], name=op.f('fk_claim_evidence_verification_id_claim_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_evidence'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_evidence')
    op.drop_table('claim_verifications')
    op.drop_table('extracted_claims')
    op.drop_table('verification_documents')
    # ### end Alembic commands ###
